default_context:
  project_name: 'aadhura'
  project_slug: 'aadhura'
  domain_main: 'aadhura.kanigam.com'
  domain_staging: 'stag.aadhura.kanigam.com'
  docker_swarm_stack_name_main: 'aadhura-kanigam-com'
  docker_swarm_stack_name_staging: 'stag-aadhura-kanigam-com'
  secret_key: '5343b31d3b8173e85cece09104f99b65b6f222d1abca711f76652a96da65d134'
  first_superuser: 'admin@aadhura.kanigam.com'
  first_superuser_password: 'Aadhura@1234'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.aadhura.kanigam.com", "https://stag.aadhura.kanigam.com", "https://aadhura.kanigam.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@aadhura.kanigam.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'postgres'
  traefik_constraint_tag: 'aadhura.kanigam.com'
  traefik_constraint_tag_staging: 'stag.aadhura.kanigam.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Aadhura@1234'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
